app/routes.php
<?php

//================================================
// Rotas públicas
//================================================
Route::controller('auth', 'AuthController');
Route::get('/', function() {
    return Redirect::to('auth/login');
});

//================================================
// Rotas restritas ao usuário autenticado
//================================================

Route::group(array('before' => 'usuario-externo'), function() {

    Route::controller('home', 'PublicaHomeController');

});

//================================================
// Rotas restritas ao usuário com acesso ao back-office
//================================================
Route::group(array('before' => 'backoffice', 'prefix' => 'admin'), function() {

    Route::get('/', function() {
        return Redirect::to('admin/home');
    });

    Route::controller('home', 'HomeController');

    Route::group(array('before' => 'empresa'), function() {

        Route::controller('pessoa', 'PessoaController');
        Route::controller('potpourri', 'PoutporritController');
        Route::controller('sociedade', 'SociedadeController');
        Route::controller('titular', 'TitularController');

        // Cadastros
        Route::controller('categoria', 'CategoriaController');
        Route::controller('contato', 'ContatoController');
        Route::controller('coletivo', 'ColetivoController');
        Route::controller('empresa', 'EmpresaController');
        Route::controller('endereco', 'EnderecoController');
        Route::controller('exportacao', 'ExportacaoController');
        Route::controller('fonograma', 'FonogramaController');
        Route::controller('fonogramaobras', 'FonogramaObrasController');
        Route::controller('fonogramapoutporrit', 'FonogramaPoutporritController');
        Route::controller('fonogramacoletivos', 'FonogramaColetivosController');
        Route::controller('fonogramatitulares', 'FonogramaTitularesController');
        Route::controller('genero', 'GeneroController');
        Route::controller('instrumento', 'InstrumentoController');
        Route::controller('obra', 'ObraController');
        Route::controller('obratitulares', 'ObraTitularesController');
        Route::controller('pais', 'PaisController');
        Route::controller('pseudonimo', 'PseudonimoController');
        Route::controller('telefone', 'TelefoneController');
        Route::controller('tipomidia', 'TipoMidiaController');
        Route::controller('tipoproduto', 'TipoProdutoController');

        // Controle de acesso
        Route::controller('perfil', 'PerfilController');
        Route::controller('usuario', 'UsuarioController');
    });
});

//================================================
// Rotas restritas ao back-office
//================================================
Route::group(array('before' => 'usuario-externo'), function() {

});

app/models/Obra.php
<?php
/**
 * @property int $id_tipo_fonograma
 * @property string $dsc_tipo_fonograma Nome
 * @property string $Ind_Situacao
 * @property string $ind_trilha
 * @property datetime created_at
 * @property datetime updated_at
 *
 */
class Obra extends Modelo {
    protected $table = 'obra';
    protected $primaryKey = 'id_obra';
    protected $guarded = array();

    public static function boot()
    {
        parent::boot();

        static::creating(function($model)
        {
            $model->id_empresa = \Auth::user()->id_empresa;
        });
    }

    public function obratitulares(){
        return $this->hasMany('ObraTitular', 'id_obra', 'id_obra');
    }

    public function getNomesTitularesAttribute(){
        $obraTitulares = $this->obratitulares();
        $ret = '';
        $br = '';
        foreach($obraTitulares as $obraTitular){
            $ret .= $br.$obraTitular->titular->pessoa->fantasia;
            $br = '<br/>';
        }
        return $ret;
    }

    public function genero(){
      return $this->belongsTo('Genero', 'id_genero', 'id_genero');
    }

    public function scopeTitulo($query, $filtro){
        return $query->orWhere('titulo_original', 'like', '%'.$filtro.'%');
    }

    public function scopeFiltro($query, $filtro){
        if (trim($filtro) != ''){
            $filtro = "%".$filtro."%";
            $sql = " (  titulo_original like '".$filtro."'
                             or subtitulo like '".$filtro."'
                             or cod_obra_ecad like '".$filtro."'
                             or cod_ISWC  like '".$filtro."'
                             or id_obra in (select obra.id_obra
                                              from obra_titular, titular, pessoa, obra
                                             where titular.id_titular = obra_titular.id_titular
                                               and pessoa.id_pessoa = titular.id_pessoa
                                               and obra_titular.id_obra = obra.id_obra
                                               and pessoa.nome_razao like '".$filtro."')
                            or id_obra in (select obra.id_obra
                                            from obra_titular, titular, pessoa, titular_pseudonimo, obra
                                           where titular.id_titular = obra_titular.id_titular
                                             and pessoa.id_pessoa = titular.id_pessoa
                                             and obra_titular.id_obra = obra.id_obra
                                             and titular_pseudonimo.id_titular = titular.id_titular
                                             and titular_pseudonimo.pseudonimo like '".$filtro."')
                            )";
            $query->whereRaw($sql);
        }

        return $query;

    }

    function pode_excluir(){
        $qtd_fonograma = \Fonograma::where('id_obra', '=', $this->id_obra)->count();
        if ($qtd_fonograma > 0){
            return false;
        } else {
            return true;
        }
    }
}

app/controllers/FonogramaController.php
<?php

class FonogramaController extends BaseController {

    public function getIndex() {
        $rep = new \ISRC\Repositorios\RepositorioFonograma;
        $regs = $rep->registrosConsulta();
        return View::make('fonograma.index')
                        ->with('regs', $regs);
    }

    public function postIndex() {
        Input::flash();
        $rep = new \ISRC\Repositorios\RepositorioFonograma;
        $regs = $rep->registrosConsulta(Input::get('filtro'));
        return View::make('fonograma.index')
                        ->with('regs', $regs);
    }

    public function getEdit($id = 0, $id_obra = null, $id_poutporrit = null) {
        if ($id > 0) {
            $reg = \Fonograma::find($id);
            $titulo = 'Editar fonograma';
        } else {
            $titulo = 'Cadastrar novo fonograma';
            $reg = new \Fonograma;
            $reg->id_obra = $id_obra;
            $reg->id_poutporrit = $id_poutporrit;
            $reg->is_gravacao_propria = 1;
        }
        $generos = \Genero::comboComDefault();
        $tipos_midia = \TipoMidia::comboComDefault();
        $tipos_fonograma = \TipoFonograma::comboComDefault();
        $tipos_produto = \TipoProduto::comboComDefault();
        $arranjos = \Arranjo::comboComDefault();
        $paises = \Pais::comboComDefault();
        $fonograma_titulares = $reg->fonogramatitulares;
        $tipos_fonograma_trilha = \TipoFonograma::trilhas();
        $arranjos_precisam_complemento = \Arranjo::precisam_complemento();

        return View::make('fonograma.edit')
                        ->with('objeto', $reg)
                        ->with('titulo', $titulo)
                        ->with('generos', $generos)
                        ->with('tipos_midia', $tipos_midia)
                        ->with('tipos_fonograma', $tipos_fonograma)
                        ->with('tipos_produto', $tipos_produto)
                        ->with('arranjos', $arranjos)
                        ->with('paises', $paises)
                        ->with('fonograma_titulares', $fonograma_titulares)
                        ->with('tipos_fonograma_trilha', $tipos_fonograma_trilha)
                        ->with('arranjos_precisam_complemento', $arranjos_precisam_complemento)
        ;
    }

    public function postEdit() {
        $post = Input::all();
        try {
            $rep = new \ISRC\Repositorios\RepositorioFonograma;
            $fono = $rep->salve($post);
            if ($fono) {
                Session::flash('msg', 'Fonograma atualizado com sucesso');
                return Redirect::to('/admin/fonograma/edit/' . $fono->id_fonograma);
            } else {
                Input::flash();
                Session::flash('error', $rep->getErrors());
                return Redirect::to('/admin/fonograma/edit/'  . $post['id_fonograma']);
            }
        } catch (Exception $ex) {
            Input::flash();
            Session::flash('error', $ex->getMessage().$ex->getTraceAsString());
            return Redirect::to('/admin/fonograma/edit/' . $post['id_fonograma']);
        }
    }

    public function getSelecionarobra($id_fonograma) {
        $fonograma = \Fonograma::find($id_fonograma);
        $obra = $fonograma->obra;
        return View::make('obra.seleciona')
                        ->with('obra', $obra)
        ;
    }

    public function getCriar($tipo, $id) {
        $titulo = 'Cadastrar novo fonograma';
        $reg = new \Fonograma;
        if ($tipo == 'obra') {
            $reg->id_obra = $id;
            $obra = \Obra::find($id);
            $nome_obra = '(' . $id . ') ' . $obra->titulo_original;
        } else {
            $reg->id_poutporrit = $id;
            $pot = \Poutporrit::find($id);
            $nome_obra = '(' . $id . ') ' . $pot->nome;
        }


        $generos = \Genero::comboComDefault();
        $tipos_midia = \TipoMidia::comboComDefault();
        $tipos_fonograma = \TipoFonograma::comboComDefault();
        $arranjos = \Arranjo::comboComDefault();
        $paises = \Pais::comboComDefault();

        return View::make('fonograma.criar')
                        ->with('objeto', $reg)
                        ->with('titulo', $titulo)
                        ->with('generos', $generos)
                        ->with('tipos_midia', $tipos_midia)
                        ->with('tipos_fonograma', $tipos_fonograma)
                        ->with('arranjos', $arranjos)
                        ->with('paises', $paises)
                        ->with('nome_obra', $nome_obra)
        ;
    }

    public function postCriar() {
        Input::flash();
        $post = Input::all();
        try {
            $rep = new \ISRC\Repositorios\RepositorioFonograma;
            $rep->salve($post);
            Session::flash('msg', 'Fonograma atualizado com sucesso');
            return Redirect::to('/admin/fonograma/edit/' . $post['id_fonograma']);
        } catch (Exception $ex) {
            Input::flash();
            Session::flash('error', $ex->getMessage());
            return Redirect::to('/admin/fonograma/edit/' . $post['id_fonograma']);
        }
    }

    public function postAlterarobra() {
        $id_fonograma = Input::get('id_fonograma');
        $id_obra = Input::get('id_obra');
        $fono = \Fonograma::find($id_fonograma);
        $fono->id_obra = $id_obra;
        $fono->save();
        $ret['codret'] = 0;
        $ret['msg'] = 'Obra alterada com sucesso!';
        return $ret;
    }

    public function postArquivo() {
        try {
            if (Input::hasFile('arquivo')) {
                $arquivo = Input::file('arquivo');
                $fono = \Fonograma::find(Input::get('id_fonograma'));
                $fono->armazenarArquivo($arquivo);
                Session::flash('msg', 'Fonograma atualizado com sucesso');
            } else {
                Session::flash('msg', 'Arquivo não recebido. Tente novamente.');
            }
        } catch (Exception $ex) {
            Input::flash();
            Session::flash('error', $ex->getMessage());
        }
        return Redirect::to('/admin/fonograma/edit/' . Input::get('id_fonograma'));
    }

    public function getDownload($id_fonograma) {
        $fono = \Fonograma::find($id_fonograma);
        $headers = array(
            'Content-Type: ' . $fono->mimetype_arquivo,
        );
        return Response::download($fono->caminhoArquivo(), "fonograma_" . $id_fonograma . "." . $fono->extensao_arquivo, $headers);
    }

    public function getRecalcular($id_fonograma){
        try{
            $rep = new \ISRC\Repositorios\RepositorioFonograma;
            $rep->calculaRateio($id_fonograma);
            Session::flash('msg', 'Percentuais recalculados com sucesso!');
        }
        catch(Exception $ex){
            Session::flash('error', $ex->getMessage());
        }
        return Redirect::to('/admin/fonograma/edit/' . $id_fonograma. "#containerFonogramaTitulares");
     }
}

app/views/fonograma/abas.blade.php
<?
$abas = array(
    'Fonograma' => array(
                    'titulo' => '<i class="fa fa-microphone"></i> Fonograma'    
                  , 'link' => "/admin/fonograma/edit/".$objeto->id_fonograma
                  , 'toggle' => ''
                  , 'ativo' => ''
                ),
    'Pot-pourri' => array('titulo' => '<i class="fa fa-flask"></i> Pot-pourri'    , 'link' => "/admin/fonogramapoutporrit/show/".$objeto->id_fonograma, 'toggle' => '', 'ativo' => ''),
    'Titulares' => array('titulo' => '<i class="fa fa-user"></i> Titulares'    , 'link' => "/admin/fonogramatitulares/show/".$objeto->id_fonograma, 'toggle' => '', 'ativo' => '')
);
$abas[$abaAtiva]['link'] = '#tab_1_1_1';
$abas[$abaAtiva]['toggle'] = 'data-toggle="tab"';
$abas[$abaAtiva]['ativo'] = 'class="active"';
?>

<ul class="nav nav-tabs nav-justified">
    @foreach($abas as $aba)
    <li {{$aba['ativo']}}><a href="{{$aba['link']}}" {{$aba['toggle']}}> {{$aba['titulo']}}</a></li>
    @endforeach
</ul>

app/views/fonograma/coletivo_pesquisa.blade.php
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
    <h4 class="modal-title">Adicionar coletivo</h4>
</div>
<div class="modal-body">
    {{Form::open(array('role' => "form", "class" => "form-horizontal", "id" => "fmrTitularPesquisar"))}}
    <div class="form-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label class="col-md-3 control-label">Nome</label>
                    <div class="col-md-9">
                        <div class="input-group">
                        {{Form::text('nome_razao', $nome_razao, array("class" => "form-control", "id"=> 'nome_razao', "onkeypress" =>"return noenter()"))}}
                            <span class="input-group-btn">
                                <a  class="btn blue" href="javascript:btnColetivoPesquisarClick();">Pesquisar</a>
                            </span>  
                        </div>  
                    </div>
                </div>
            </div>
        </div>
    </div>
    {{Form::close()}}
    <div class="row">
        <div class="col-md-12">
            <table class="table table-stripped table-condensed table-hover">
                <colgroup>
                    <col style="width:60px;"/>
                    <col style="width:40px;"/>
                    <col style="width:auto;"/>
                </colgroup>
                <thead>
                    <tr>
                        <th class="center">Ações</th>
                        <th class="center">Id</th>
                        <th class="left">Coletivo</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($coletivos as $coletivo)
                    <tr>
                        <td class="center">
                            <a onClick="javascript:getDetalharColetivo({{$id_fonograma}},{{$coletivo->id_coletivo}});" class="btn btn-xs green-meadow" title="Incluir esse coletivo no fonograma"><i class="fa fa-arrow-right"></i></a>
                        </td>
                        <td>{{$coletivo->id_coletivo}}</td>
                        <td style="text-align:left">{{$coletivo->nome}}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            {{$msg_limite}}
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" data-dismiss="modal" class="btn red">Cancelar</button>
</div>

app/views/fonograma/coletivos.blade.php
@extends('base')

@section('estilos')
@stop

@section('conteudo')
<div class="row">
    <div class="col-md-12">
        <h3 class="page-title">Editar fonograma</h3>
    </div>
</div>
@include('_padroes.mensagens')
<div class="row">
    <div class="col-md-12">
        <div class="tabbable-custom nav-justified">
            <ul class="nav nav-tabs nav-justified">
                <li><a href="/admin/fonograma/edit/{{$objeto->id_fonograma}}" > Fonograma</a></li>
                <li><a href="/admin/fonogramaobras/show/{{$objeto->id_fonograma}}" > Obras </a></li>
                <li><a href="/admin/fonogramatitulares/show/{{$objeto->id_fonograma}}" > Titulares conexos </a></li>
                <li class="active"><a href="#tab_1_1_1" data-toggle="tab"> Coletivos </a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="tab_1_1_1">

                    <div class="portlet box yellow-gold">
                        <div class="portlet-title">
                            <div class="caption"><i class="fa fa-gift"></i> Titulares conexos</div>
                            <div class="tools">
                            </div>
                        </div>
                        <div class="portlet-body form">
                            <div class="table-scrollable">
                                @include('_padroes.table')
                                <thead>
                                    <tr>
                                        <th class="center">Ações</th>
                                        <th class="center">Id</th>
                                        <th class="left">Título</th>
                                        <th class="center">Cód.<br/>Gravadora</th>
                                        <th class="center">Cód. ISRC</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($regs as $reg)
                                    <tr>
                                        <td class="center">
                                            <a href="{{URL::to('/admin/fonograma/edit/'.$reg->id_fonograma)}}" class="btn btn-sm green-seagreen" title="Editar"><i class="fa fa-edit"></i></a>
                                        </td>
                                        <td class="center">{{$reg->id_fonograma}}</td>
                                        <td>{{$reg->titulo}}</td>
                                        <td class="center">{{$reg->cod_GRA}}</td>
                                        <td class="center">{{$reg->Cod_ISRC_fmt}}</td>
                                    </tr>
                                    @endforeach
                                </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                    <div class="portlet box yellow-gold">
                        <div class="portlet-title">
                            <div class="caption"><i class="fa fa-gift"></i> Titulares conexos</div>
                            <div class="tools">
                            </div>
                        </div>
                        <div class="portlet-body form">
                            {{Form::open(array('role' => "form", "class" => "form-horizontal"))}}
                            {{Form::hidden('id_fonograma', $objeto->id_fonograma)}}
                            <div class="form-body">
                                <a class=" btn default" href="/admin/fonograma/selecionarobra/{{$objeto->id_fonograma}}" data-target="#ajax" data-toggle="modal">
                                    View Demo </a>
                                <h4>Códigos</h4>
                                <div class="form-group">
                                    <label class="col-md-3 control-label">ISRC</label>
                                    <div class="col-md-9">
                                        {{Form::text('Cod_ISRC', Input::old('Cod_ISRC', $objeto->Cod_ISRC), array("class" => "form-control"))}}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-3 control-label">Gravadora</label>
                                    <div class="col-md-9">
                                        {{Form::text('cod_GRA', Input::old('cod_GRA', $objeto->cod_GRA), array("class" => "form-control"))}}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-3 control-label">Data de emissão</label>
                                    <div class="col-md-9">
                                        {{Form::text('dt_emissao_fmt', Input::old('dt_emissao_fmt', $objeto->dt_emissao_fmt), array("class" => "form-control"))}}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-3 control-label">Catálogo</label>
                                    <div class="col-md-9">
                                        {{Form::text('num_catalogo', Input::old('num_catalogo', $objeto->num_catalogo), array("class" => "form-control"))}}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-3 control-label">Obra</label>
                                    <div class="col-md-9">
                                        {{Form::text('num_catalogo', Input::old('num_catalogo', $objeto->num_catalogo), array("class" => "form-control"))}}
                                    </div>
                                </div>
                            </div>
                        </div>
                        {{Form::close()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="ajax" role="basic" aria-hidden="true">
    <div class="page-loading page-loading-boxed">
        <img src="/assets/global/img/loading-spinner-grey.gif" alt="" class="loading">
        <span>
            &nbsp;&nbsp;Loading... </span>
    </div>
    <div class="modal-dialog">
        <div class="modal-content">
        </div>
    </div>
</div>
</div>
@stop
@section('scripts')
ComponentsPickers.init();
$('#menuAcesso').addClass('active');
$('#menuAcesso').addClass('open');
$('#itemPerfis').addClass('active');
@stop

app/views/fonograma/formPesquisa.blade.php
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
        <h4 class="modal-title">Adicionar titular</h4>
    </div>
    <div class="modal-body">
        {{Form::open(array('role' => "form", "class" => "form-horizontal", "id" => "fmrTitularPesquisar"))}}
        <div class="form-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label class="col-md-3 control-label">Nome</label>
                        <div class="col-md-9">
                            <div class="input-group">
                            {{Form::text('nome_razao', '', array("class" => "form-control", "id"=> 'nome_razao', "onkeypress" =>"return noenter()"))}}
                                <span class="input-group-btn">
                                    <a  class="btn blue" href="javascript:btnTitularPesquisarClick();">Pesquisar</a>
                                </span>  
                            </div>  
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {{Form::close()}}
        <div id="msg" style="color:red;"></div>
    </div>
    <div class="modal-footer">
        <button type="button" data-dismiss="modal" class="btn red">Cancelar</button>
    </div>  

app/views/fonograma/formPesquisaColetivo.blade.php
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
    <h4 class="modal-title">Adicionar coletivo</h4>
</div>
<div class="modal-body">
    {{Form::open(array('role' => "form", "class" => "form-horizontal", "id" => "fmrColetivoPesquisar"))}}
    <div class="form-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label class="col-md-3 control-label">Nome</label>
                    <div class="col-md-9">
                        <div class="input-group">
                        {{Form::text('nome_razao', '', array("class" => "form-control", "id"=> 'nome_razao', "onkeypress" =>"return noenter()"))}}
                            <span class="input-group-btn">
                                <a  class="btn blue" href="javascript:btnColetivoPesquisarClick();">Pesquisar</a>
                            </span>  
                        </div>  
                    </div>
                </div>
            </div>
        </div>
    </div>
    {{Form::close()}}
    <div id="msg" style="color:red;"></div>
</div>
<div class="modal-footer">
    <button type="button" data-dismiss="modal" class="btn red">Cancelar</button>
</div>            

app/views/fonograma/obras.blade.php
@extends('base')

@section('estilos')
@stop

@section('conteudo')
<div class="row">
    <div class="col-md-12">
        <h3 class="page-title">Editar fonograma - Obra</h3>
    </div>
</div>
@include('_padroes.mensagens')
<div class="row">
    <div class="col-md-12">
        <div class="tabbable-custom nav-justified">
            <ul class="nav nav-tabs nav-justified">
                <li><a href="/admin/fonograma/edit/{{$objeto->id_fonograma}}" > Fonograma</a></li>
                <li class="active"><a href="#tab_1_1_1" data-toggle="tab"> Obra  </a></li>
                <li><a href="/admin/fonogramapoutporrit/show/{{$objeto->id_fonograma}}" > Poutporrit </a></li>
                <li><a href="/admin/fonogramatitulares/show/{{$objeto->id_fonograma}}" > Titulares conexos </a></li>
                <li><a href="/admin/fonogramacoletivos/show/{{$objeto->id_fonograma}}" > Coletivo </a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="tab_1_1_1">

                    <div class="portlet box yellow-gold">
                        <div class="portlet-title">
                            <div class="caption"><i class="fa fa-gift"></i> Obra atual</div>
                            <div class="tools">
                            </div>
                        </div>
                        <div class="portlet-body">
                            <div class="form-body">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            {{Form::text('nome_obra', $objeto->nome_obra, array("class" => "form-control", "disabled"))}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="portlet box yellow-gold">
                        <div class="portlet-title">
                            <div class="caption"><i class="fa fa-gift"></i> Alterar obra</div>
                            <div class="tools">
                            </div>
                        </div>
                        <div class="portlet-body">
                            {{Form::open(array('role' => "form", "class" => "form-horizontal"))}}
                            <div class=" form form-body">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="input-group">
                                            {{Form::text('pesquisar', Input::old('pesquisar'), array("class" => "form-control"))}}
                                            <span class="input-group-btn"><button class="btn" ><i class="fa fa-search"></i> Filtrar</button></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            @if ($obras)
                            {{$obras->appends(array('pesquisar' => $pesquisar))->links()}}
                            @endif
                            {{Form::close()}}
                            @include('_padroes.table')
                            <colgroup>
                                <col style="width:60px;"/>
                                <col style="width:100px;"/>
                                <col style="width:auto;"/>                                
                            </colgroup>
                            <thead>
                                <tr>
                                    <th class="center">Ações</th>
                                    <th class="center">Id</th>
                                    <th class="left">Nome</th>
                                    <th class="left">Artistas</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($obras as $obra)
                                <tr>
                                    <td class="center">
                                        <a href="{{URL::to('/admin/fonogramaobras/set/'.$objeto->id_fonograma.'/'.$obra->id_obra)}}" class="btn btn-sm purple-studio" title="Editar"><i class="fa fa-thumb-tack"></i></a>
                                    </td>
                                    <td class="center">{{$obra->id_obra}}</td>
                                    <td>{{$obra->titulo_original}}</td>
                                    <td>{{$obra->nomes_titulares}}</td>
                                </tr>
                                @endforeach
                            </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="ajax" role="basic" aria-hidden="true">
    <div class="page-loading page-loading-boxed">
        <img src="/assets/global/img/loading-spinner-grey.gif" alt="" class="loading">
        <span>
            &nbsp;&nbsp;Loading... </span>
    </div>
    <div class="modal-dialog">
        <div class="modal-content">
        </div>
    </div>
</div>
@stop
@section('scripts')
ComponentsPickers.init();
$('#menuAcesso').addClass('active');
$('#menuAcesso').addClass('open');
$('#itemPerfis').addClass('active');
@stop